= Tareas pendientes de Asalto y castigo
:revdate: 2016-07-11

== Programación

2016-07-10:

Estudiar si la configuración `repeat-previous-action?` es útil.

2016-07-10:

Configurar opción para español americano.

2016-07-09:

Error:

----
  > deja espada con ertueourt usando uceue
  Parece haber un complemento (seudo)preposicional sin completar en el comando. Sé más
claro.
  > deja espada con capa usando uceue
  Se identifica un complemento (seudo)preposicional sin completar en el texto. Exprésate
más sencillamente, por favor.
  > deja espada con capa usando coraza
  Dejas tu espada.
----

2016-07-07:

Error, no hay respuesta en las repeticiones de «ahuyéntala»:

----
El pasaje sigue de norte a sur.
Una serpiente está bloqueando el paso al sur.
Puedes ver una serpiente.
> mira serpiente
Una serpiente grande, muy atenta a tu más mínimo movimiento.
> ahuyéntala
Sorprendida por los amenazadores tajos, la serpiente se esconde.
> ahuyéntalo
Sé más claro, por favor, no se reconoce ningún complemento principal en el comando.
> ahuyéntala
> ahuyéntala
> ahuyéntala
> ahuyéntala
----

2016-07-06:

Hacer que los errores asociados a los filtros de acción sean
configurables por la aplicación (en Flibustre).

2016-07-06:

Error tras matar la serpiente:

----
  Pasaje de la serpiente [#43]
  El paso sigue de norte a sur.
  > ex serpiente
  No ves ninguna espada.
  > coge serpiente
  Por aquí no hay ninguna serpiente.
  > i
  Tienes tu capa (puesta), tu coraza (puesta), un pedernal, tu espada y una antorcha.
  > ex serpiente
  No puedes ver tal cosa.
  > ex serpiente
  No ves esa cosa.
  > ex serpiente
  No se ve ninguna serpiente.
  >
----

2016-07-06:

Mejores mensajes para las acciones combinadas, como cuando se deja una
prenda puesta.

2016-06-26:

Añadir un comando inmediato para que el jugador pueda dar un comando
de configuración.

2016-06-26:

Confirmar esto que se dice en el fichero de configuración:

____
El color de fondo de la pantalla es configurable pero con una
limitación: cuando la pantalla se enrolla (se desplaza hacia arriba)
el color del sistema se utilizará en las nuevas líneas que aparezcan
por debajo.
____

2016-06-25:

Hacer que la acción previa sea anulada tras un error.

2016-02-03:

Fallo: Si el jugador escribe algo pero no se reconoce ninguna palabra,
se repite todo el comando anterior.

En realidad no es un fallo, es fruto de la variable
`repeat_previous_action?`, que se puede configurar en el fichero de
configuración.

----
  Todos tus hombres lo celebran.
  > habla
  Intentar hablar solo es ilógico.
  > come
  No tiene lógica ninguna hablar con uno mismo.
  > come
  Hablarse a uno es ilógico.
  > ueuo
  No parece lógico hablarse a sí.
  > ueortuoe
  Intentar hablar solo es ilógico.
  > ueorcueou
  No tiene sentido hablar con uno mismo.
----

'''
2012-10-04:

Si falta verbo en el comando, usar el último válido.  Esta
opción será configurable.

'''
2012-09-19:

Error:

----
  Hecho.
  > i
  Llevas contigo tu capa (puesta), tu coraza (puesta), el
pedernal, tu espada y una antorcha.
  > ex espada
  Main : espada
  Legado de tu padre, fiel herramienta en mil batallas.
  > déjala
  Main : espada
  Hecho.
  > m
  Recodo arenoso del canal
  La fuerte corriente, de Norte a Este, impide el paso, excepto al
Oeste. Al fondo puede oírse un gran estruendo.
  Ves tu espada.
  > cógela
  Main : pedernal
  Ya llevas eso contigo.
  >
----

'''
2012-05-16:

----
> deja espada
> s
> mira espada
No ves eso. [y variantes]
----

Nuevo mesaje: "Aquí no está tu espada".

'''
2012-05-14:

Hacer mensajes genéricos en respuesta a comandos imposibles,
que dependan de las circunstancias:
«el jaleo de la batalla te hace desvariar»,
«la falta de aire...»

'''
2012-03-01:

Error: «No se ve ningunas velas». No es incorrecto, pero queda
mejor poner el verbo en plural en ese caso, con velas como
sujeto en lugar de «se», y «se» como reflexivo.

'''
2012-02-29, 2016-07-04:

Ideas para facilitar la depuración:

- comando #get para apropiarse de cualquier ente, esté donde esté.
- comando #go para elegir escenario por su número

'''
2012-02-20:

Añadir «hierba» y «hiedra» al escenario
location_47% , pues se citan al abrir la puerta.
Hacer que aparezcan al mencionarlas,
o al examinar la puerta o el suelo.

'''
2012-02-20:

cambiar "tu benefactor te sigue"
por "tu benefactor te acompaña",
salvo tras movimientos.

'''
2012-02-20:

Mostrar mensajes completos y variables al final de cada
acción, en lugar de "Hecho".

'''

2012-01-03:

Tras el análisis, detectar:

Preposición con artículo (al, del) que no concuerde en
género y número con su ente.

'''

2011-12:

Hacer que Gforth encuentre ayc.ini en su ruta de búsqueda
de forma trasparente.

'''

Desambiguar «hombre» para evitar «no se ve a nadie»
al decir «m hombre» en presencia de soldados.

'''

Implementar tres niveles en mirar:

0 = mirar
1 = examinar
2 = registrar

¿O hacer que sean acciones efectivas separadas?

'''

2011-12:

Poner de un color diferente, configurable, el presto y el
texto de las respuestas al sistema (preguntas sí/no).

'''

2011-12:

Los comandos de configuración no evitan que el análisis dé
error por falta de comandos del juego!

Esto es fácil de arreglar:

¿Hacer que anulen todo lo que siga?
¿O que continúen como si fuera un comando nuevo?
O mejor: simplemente rellenar ACTION con un xt
de una acción que no haga nada!

No! Lo que hay que hacer es ejecutar las acciones de
configuración como el resto de acciones, metiendo su xt en
'action'.  Y si después queremos seguir (dependerá de la
acción de sistema de que se trata) basta poner 'action' a cero
otra vez. O se puede leer el resto del comando, para
anularlo!

'''

2011-12:

Comprobar si el hecho de no usar el número máximo de líneas
causa problemas con diferentes tamaños de consola.

Los textos son cortos, de modo que no hay riesgo de
que se pierdan antes poder leerlos, antes de que
se pida entrada a un comando.

'''

2011-12:

Hacer un comando que lea el fichero de
configuración en medio de una partida.

'''

2011-12:

Implementar transcripción en fichero.

2014-02-16: el nombre del fichero puede ser automático, con fecha iso.
así basta un comando para activar y otro para desactivar la
trascripción.

'''

2011-12:

Anotar que ha habido palabras no reconocidas, para variar el error en
lugar de actuar como si faltaran.  p.e. mirar / mirar xxx.

'''

2011-12:

Hacer más naturales los mensajes que dicen
que no hay nada de interés en la dirección indicada,
p.e.,
miras hacia...
intentas vislumbrar (en la cueva oscura)...
contemplas el cielo...
miras a tus pies...

'''

2011-12:

Añadir variante:
«No observas nada digno de mención al mirar hacia el Este».

'''

2011-12:

Añadir «tocar».

'''

2011-12:

Implementar que «todo» pueda usarse
con examinar y otros verbos, y se cree una lista
ordenada aleatoriamente de entes que cumplan
los requisitos.

'''

2011-12:

Hacer algo así en las tramas del laberinto:

(una vez de x se equivoca)

: this_place_seems_familiar  ( -- )
  my_location is_visited?
  if  s" Este sitio me suena"  then ;

'''

2011-12:

Respuesta a mirar como en «Pronto»:

Miras, pero no ves eso por aquí. ¿Realmente importa?

'''

2011-12:

Crear ente «general» para el general enemigo, con
descripción durante la batalla, dependiendo de la fase.

'''

2011-12:

Implementar «describir», sinónimo de examinar para entes
presentes pero que funciona con entes no presentes ya
conocidos!

'''

2011-12:

Implementar «esperar» («z»)

'''

2011-12:

Hacer más robusto el analizador con:

«todo», «algo»

«ahora»:

----
>coge libro
>ahora la espada
>y ahora la espada
>y la espada
>también la espada
>y también la espada
>y además la espada
>además la espada
----

nombres sueltos, ¿mirarlos?:

----
>espada
Es muy bonita.
----

'''

2011-12:

Hace que «examinar» sin más examine todo.

¿Y también «coger» y otros?

coger sin objeto buscaría qué hay.
si solo hay una cosa para coger, la coge.
si hay varias, error.

'''

2011-12:

Error nuevo para no coger las cosas de la casa de Ambrosio:
Es mejor dejar las cosas de Ambrosio donde están.

Añadir a la ficha con su xt.

'''

2011-12:

Solucionar el problema de los sinónimos que no tienen
el mismo género o número...

La palabra del vocabulario podría ponerse a sí misma como
nombre del ente... Pero esto obligaría a usar el género
y número de la ficha en las descripciones.

Algo relacionado: "arma" es femenina pero usa artículo "el";
contemplar en los cálculos de artículo.

Mirar cómo lo solucioné en «La legionela del pisto»: con una
lista de nombres separada de los datos de entes.

'''

2011-12:

¿Crear un método para dar de alta fácilmente entes
decorativos? Hay muchos en las descripciones de los
escenarios.

'''

2011-12:

Hacer que no salga el presto de pausa si las pausas son
cero.

'''

2011-12:

Crear un mensaje de error más elaborado para las acciones
que precisan objeto directo, con el infinitivo como
parámetro: «¿Matar por matar?» «Normalmente hay que matar a
alguien o algo».

'''

2011-12:

Hacer que la forma «mírate» sea compatible con «mírate la capa». Para
esto habría que distiguir dos variantes de complemento principal, y que
al asignar cualquiera de ellas se compruebe si había ya otro
complemento principal del otro tipo.

'''

2011-12:

Limitar los usos de 'print_str' a la impresión. Renombrarla.
Crear otra cadena dinámica para los usos genéricos con «+ y
palabras similares.

'''

2011-12:

Comprobar los usos de 'tmp_str'.

'''

2011-12:

Poner en fichero de configuración el número de líneas
necesario para mostrar un presto de pausa.

'''

2011-12:

Implementar opción para tener en cuenta las palabras no
reconocidas y detener el análisis.

'''

2011-12:

Poner en fichero de configuración si las palabras no
reconocidas deben interrumpir el análisis.

'''

2011-12:

Poner todos los textos relativos al protagonista en segunda
persona.

(Creo que ya está hecho).

'''

2011-12:

Añadir las salidas hacia atrás. Y
adelante. Y seguir.

'''

2011-12:

Implementar el recuerdo de la dirección del último
movimiento.

'''

2011-12:

Hacer que «salir», si no hay dirección de salida en el ente,
calcule la dirección con la del último movimiento.

'''

2011-12:

Añadir a la configuración si los errores lingüísticos deben
ser detallados (técnicos) o vagos (narrativos) o ambos.

'''

2011-12:

Hacer que primero se muestre la introducción y después
los créditos y el menú.

'''

2011:

- Mensajes de error genéricos, ej.: "Tus ideas parecen confusas, quizá
debido a la oscuridad".

- Acción de quemar, prender.

== Trama y puzles

2011..2012:

Hacer que el líder de los refugiados nos deje pasar si
dejamos el objeto (piedra o espada) allí o se lo damos.

Hace que el altar solo aparezca al examinar el puente, y la
piedra al examinar el altar.

Escenario y subtrama bajo el agua.

Distinguir nadar de bucear.

Quitarse la coraza o la capa antes de nadar (ambas son
demasiado pesadas para cruzar el lago con 100% de éxito)

No poder nadar si llevamos algo en las manos aparte de la
espada.

Posibilidad de perder la capa al nadar si no la llevamos
puesta.

== Código fuente

Unificar los comentarios de palabras que devuelven cadenas de texto:

* Devuelve mensaje de que X...
* Mensaje de que X...
* X...

Terminar de cambiar el formato de los nombres de palabras de Forth en
los textos:

De esto: «La palabra ZX , a veces, se usa como ZX2 .»
A esto: «La palabra 'zx', a veces, se usa como 'zx2'.»

Plegar las líneas que sobrepasen los 63 caracteres.

== Notas


=== Esbozo de acciones y (seudo)preposiciones

----
a, al
con, usando...
de


do_attack

atacar
atacar H
atacar O
atacar a H
atacar a H con O

do_break

romper O
romper O1 con O2

do_climb

escalar
escalar O
escalar O1 con O2

do_close:

cerrar
cerrar O
cerrar O1 con O2

do_do:

hacer?

do_drop:

soltar O
soltar O1 con O2

do_examine:

(do_exits):

salidas

do_frighten
do_go
do_go_ahead
do_go_back
do_go_down
do_go_east
do_go_in
do_go_north
do_go|do_break
do_go_out
do_go_south
do_go_up
do_go_west
do_hit
do_introduce_yourself
do_inventory
do_kill
do_look
do_look_to_direction
do_look_yourself
do_make
do_open
do_put_on
do_search
do_sharpen
do_speak
do_swim
do_take
do_take|do_eat
do_take_off
----


